########################################
# Kotlin Compiler and Daemon
########################################
kotlin.code.style=official
kotlin.incremental=true
kotlin.incremental.multiplatform=true
kotlin.caching.enabled=true
kotlin.daemon.jvmargs=-Xmx4096M
kotlin.mpp.enableCInteropCommonization=true

########################################
# Gradle JVM
########################################
org.gradle.jvmargs=--illegal-access=permit -Xmx8g -XX:+UseParallelGC -Dfile.encoding=UTF-8

########################################
# Gradle General Performance
########################################
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=false
# Activate FileSystem Watcher for accelerated local builds
org.gradle.vfs.watch=true
org.gradle.logging.level=info

########################################
# Dependency Resolution
########################################
org.gradle.dependency.verification=off
org.gradle.cache.dynamicVersionsFor=24h
org.gradle.cache.changedModulesFor=24h

########################################
# Android-specific optimisations
########################################
android.useAndroidX=true
android.nonTransitiveRClass=true

########################################
# Stable builds (optional)
########################################
# For native KMP fast builds on MacOS
kotlin.native.cacheKind=none

android.builtInKotlin=false
android.newDsl=false
